/* Config.hh. Generated by CMake for ignition-math. */

/* Version number */
#define IGNITION_MATH_MAJOR_VERSION 5
#define IGNITION_MATH_MINOR_VERSION 0
#define IGNITION_MATH_PATCH_VERSION 0

#define IGNITION_MATH_VERSION "5.0"
#define IGNITION_MATH_VERSION_FULL "5.0.0"

#define IGNITION_MATH_VERSION_NAMESPACE v5

#define IGNITION_MATH_VERSION_HEADER "Ignition math, version 5.0.0\nCopyright (C) 2014 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

/* #undef IGNITION_MATH_BUILD_TYPE_PROFILE */
/* #undef IGNITION_MATH_BUILD_TYPE_DEBUG */
/* #undef IGNITION_MATH_BUILD_TYPE_RELEASE */
